USE icarusadmin;

INSERT INTO `bb_categories` (cat_name, disp_position) VALUES ('Test category',1);
INSERT INTO `bb_config` VALUES ('o_cur_version','1.4.4'),('o_database_revision','10'),('o_searchindex_revision','2'),('o_parser_revision','2'),('o_board_title','IACT Icarus'),('o_board_desc','<p><span>Dare to fly.</span></p>'),('o_default_timezone','0'),('o_time_format','H:i:s'),('o_date_format','Y-m-d'),('o_timeout_visit','1800'),('o_timeout_online','300'),('o_redirect_delay','1'),('o_show_version','0'),('o_show_user_info','1'),('o_show_post_count','1'),('o_signatures','1'),('o_smilies','1'),('o_smilies_sig','1'),('o_make_links','1'),('o_default_lang','English'),('o_default_style','Air'),('o_default_user_group','4'),('o_topic_review','15'),('o_disp_topics_default','30'),('o_disp_posts_default','25'),('o_indent_num_spaces','4'),('o_quote_depth','3'),('o_quickpost','1'),('o_users_online','1'),('o_censoring','0'),('o_ranks','1'),('o_show_dot','0'),('o_topic_views','1'),('o_quickjump','1'),('o_gzip','0'),('o_additional_navlinks',''),('o_report_method','0'),('o_regs_report','0'),('o_default_email_setting','1'),('o_mailing_list','jmataya@iactpgh.com'),('o_avatars','1'),('o_avatars_dir','img/avatars'),('o_avatars_width','60'),('o_avatars_height','60'),('o_avatars_size','10240'),('o_search_all_forums','1'),('o_base_url','http://localhost/fluxbb'),('o_admin_email','jmataya@iactpgh.com'),('o_webmaster_email','jmataya@iactpgh.com'),('o_forum_subscriptions','1'),('o_topic_subscriptions','1'),('o_smtp_host',NULL),('o_smtp_user',NULL),('o_smtp_pass',NULL),('o_smtp_ssl','0'),('o_regs_allow','1'),('o_regs_verify','0'),('o_announcement','0'),('o_announcement_message','Enter your announcement here.'),('o_rules','0'),('o_rules_message','Enter your rules here'),('o_maintenance','0'),('o_maintenance_message','The forums are temporarily down for maintenance. Please try again in a few minutes.<br />\\n<br />\\n/Administrator'),('o_default_dst','0'),('o_feed_type','2'),('p_message_bbcode','1'),('p_message_img_tag','1'),('p_message_all_caps','1'),('p_subject_all_caps','1'),('p_sig_all_caps','1'),('p_sig_bbcode','1'),('p_sig_img_tag','0'),('p_sig_length','400'),('p_sig_lines','4'),('p_allow_banned_email','1'),('p_allow_dupe_email','0'),('p_force_guest_email','1');
INSERT INTO `bb_forums` (forum_name, forum_desc, redirect_url, moderators, num_topics, num_posts, last_post, last_post_id, last_poster, sort_by, disp_position, cat_id) VALUES ('Test forum','This is just a test forum',NULL,NULL,1,1,1300200419,1,'jmataya',0,1,1);
INSERT INTO `bb_groups` (g_title, g_user_title, g_moderator, g_mod_edit_users, g_mod_rename_users, g_mod_change_passwords, g_mod_ban_users, g_read_board, g_view_users, g_post_replies, g_post_topics, g_edit_posts, g_delete_posts, g_delete_topics, g_set_title, g_search, g_search_users, g_send_email, g_post_flood, g_search_flood, g_email_flood) VALUES ('Administrators','Administrator',0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,0,0,0),('Moderators','Moderator',1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0),('Guest',NULL,0,0,0,0,0,1,1,0,0,0,0,0,0,1,1,0,60,30,0),('Member',NULL,0,0,0,0,0,1,1,1,1,1,1,1,0,1,1,1,60,30,60);
INSERT INTO `bb_online` VALUES (1,'127.0.0.1',1300561046,0,NULL,NULL);
INSERT INTO `bb_posts` (poster, poster_id, poster_ip, poster_email, message, hide_smilies, posted, edited, edited_by, topic_id) VALUES ('jmataya',2,'127.0.0.1',NULL,'If you are looking at this (which I guess you are), the install of FluxBB appears to have worked! Now log in and head over to the administration control panel to configure your forum.',0,1300200419,NULL,NULL,1);
INSERT INTO `bb_ranks` (rank, min_posts) VALUES ('New member',0),('Member',10);
INSERT INTO `bb_search_matches` VALUES (1,1,0),(1,2,0),(1,3,0),(1,4,0),(1,5,0),(1,6,0),(1,7,0),(1,8,0),(1,9,0),(1,10,0),(1,11,0),(1,12,0),(1,13,0),(1,15,1),(1,14,1);
INSERT INTO `bb_search_words` (word) VALUES ('looking'),('guess'),('install'),('fluxbb'),('appears'),('worked'),('log'),('head'),('administration'),('control'),('panel'),('configure'),('forum'),('test'),('post');
INSERT INTO `bb_topics` (poster, subject, posted, first_post_id, last_post, last_post_id, last_poster, num_views, num_replies, closed, sticky, moved_to, forum_id) VALUES ('jmataya','Test post',1300200419,1,1300200419,1,'jmataya',0,0,0,0,NULL,1);

LOCK TABLES `bb_users` WRITE;
/*!40000 ALTER TABLE `bb_users` DISABLE KEYS */;
INSERT INTO `bb_users` VALUES (1,3,'Guest','Guest','Guest',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,0,0,1,1,1,1,1,0,0,0,0,'English','Air',0,NULL,NULL,NULL,0,'0.0.0.0',0,NULL,NULL,NULL),(2,1,'jmataya','371f98c70ca9263c4bcf2822a2eb88c929f80ddc','jmataya@iactpgh.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,0,0,1,1,1,1,1,0,0,0,0,'English','Air',1,1300200419,NULL,NULL,1300200419,'127.0.0.1',1300200622,NULL,NULL,NULL);
/*!40000 ALTER TABLE `bb_users` ENABLE KEYS */;
UNLOCK TABLES;